name: Update Localizations

on:
  push:
    branches:
      - main

jobs:
  update_localizations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install googletrans==4.0.0-rc1

    - name: Update Localizations
      run: |
        python updater.py

    - name: Check for Changes
      id: check_changes
      run: |
        git diff --quiet || echo "Changes found"
      continue-on-error: true
    
    - name: Debug Check for Changes
      run: echo "Changes found status:" + ${{ steps.check_changes.outputs.return-value }}

    - name: Commit Changes
      if: steps.check_changes.outputs.return-value == 'Changes found'
      run: |
        git config --local user.email ${{ secrets.EMAIL }}
        git config --local user.name "mr_f0rtuna4"
        git add -A
        git commit -m "Update localizations"
      env:
        GIT_COMMITTER_NAME: "mr_f0rtuna4"
        GIT_COMMITTER_EMAIL: ${{ secrets.EMAIL }}

    - name: Debug Commit Changes
      if: steps.check_changes.outputs.return-value == 'Changes found'
      run: echo "Commit changes executed."

    - name: Push Changes
      if: steps.check_changes.outputs.return-value == 'Changes found'
      run: git push
      env:
        GITHUB_TOKEN: ${{ secrets.GTK }}

    - name: Debug Push Changes
      if: steps.check_changes.outputs.return-value == 'Changes found'
      run: echo "Push changes executed."
