name: Update Localizations

on:
  push:
    branches:
      - main

jobs:
  update_localizations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install googletrans==4.0.0-rc1

    - name: Update Localizations
      run: |
        python updater.py

    - name: Check for Changes
      id: check_changes
      run: |
        git diff --quiet || echo "Changes found"
      continue-on-error: true

    - name: Commit Changes
      if: steps.check_changes.outputs.return-value == 'Changes found'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update localizations"
      
    - name: Push Changes
      if: steps.check_changes.outputs.return-value == 'Changes found'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
